# Generated by Django 5.2 on 2025-04-21 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0004_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="watchlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="watchlist_app.watchlist",
            ),
        ),
    ]
